Repository WildCodeSchool/tours-projet2-jjd, pull requests merged in 2019-04, with the labels that each got.

#1 Template
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/component/body/body.component.css
  src/app/component/body/body.component.html
  src/app/component/body/body.component.spec.ts
  src/app/component/body/body.component.ts
  src/app/component/dashboard/dashboard.component.css
  src/app/component/dashboard/dashboard.component.html
  src/app/component/dashboard/dashboard.component.spec.ts
  src/app/component/dashboard/dashboard.component.ts
  src/app/component/datepicker/datepicker.component.css
  src/app/component/datepicker/datepicker.component.html
  src/app/component/datepicker/datepicker.component.spec.ts
  src/app/component/datepicker/datepicker.component.ts
  src/app/component/footer/footer.component.css
  src/app/component/footer/footer.component.html
  src/app/component/footer/footer.component.spec.ts
  src/app/component/footer/footer.component.ts
  src/app/component/home/home.component.css
  src/app/component/home/home.component.html
  src/app/component/home/home.component.spec.ts
  src/app/component/home/home.component.ts
  src/app/component/navbar/navbar.component.css
  src/app/component/navbar/navbar.component.html
  src/app/component/navbar/navbar.component.spec.ts
  src/app/component/navbar/navbar.component.ts
  src/assets/image/logo.png
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/styles.css
  src/test.ts
Labels: Doing

#2 PR Sprint semaine 2 - branche Booking.
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/component/booking/booking.component.css
  src/app/component/booking/booking.component.html
  src/app/component/booking/booking.component.spec.ts
  src/app/component/booking/booking.component.ts
  src/app/component/navbar/navbar.component.html
  src/app/core/models/booking.ts
  src/app/services/booking.service.spec.ts
  src/app/services/booking.service.ts
Labels: Done, good first issue

#5 Feature get routing
  src/app/component/body/body.component.html
  src/app/component/booking/booking.component.css
  src/app/component/booking/booking.component.html
  src/app/component/establishment/etablishement.component.css
  src/app/component/establishment/etablishement.component.html
  src/app/component/navbar/navbar.component.html
  src/app/component/profile/profile.component.css
  src/app/component/profile/profile.component.html
  src/styles.css
Labels: Done

#10 Feature caroussel // Jérémy // modif home page avant fusion
  src/app/app.module.ts
  src/app/component/body/body.component.css
  src/app/component/body/body.component.html
  src/app/component/establishment/etablishement.component.css
  src/app/component/establishment/etablishement.component.html
  src/app/component/forgot/forgot.component.html
  src/assets/image/Capture du 2019-04-23 17-17-27.png
  src/assets/image/appstore1.png
  src/assets/image/badge_new.png
  src/assets/image/bar.jpg
  src/assets/image/cafe.jpg
  src/assets/image/map.png
  src/assets/image/reserv.png
  src/assets/image/resto.jpg
  src/assets/image/sold.png
  src/styles.css
Labels: Done

#11 home img responsive service auth component registration
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/component/body/body.component.css
  src/app/component/body/body.component.html
  src/app/component/booking/booking-list/booking-list.component.html
  src/app/component/establishment/establishment-list/establishment-list.component.html
  src/app/component/login/login.component.html
  src/app/component/navbar/navbar.component.html
  src/app/component/registration/registration.component.css
  src/app/component/registration/registration.component.html
  src/app/component/registration/registration.component.spec.ts
  src/app/component/registration/registration.component.ts
  src/app/services/authentication.service.spec.ts
  src/app/services/authentication.service.ts
Labels: Done

#14 modif home page ==> anglais, modif formulaire style profile
  src/app/component/body/body.component.css
  src/app/component/body/body.component.html
  src/app/component/booking/booking.component.css
  src/app/component/booking/booking.component.html
  src/app/component/establishment/etablishement.component.css
  src/app/component/profile/profile.component.css
Labels: Done

#35 feature-dylanissues1
  package-lock.json
  package.json
  src/app/component/body/body.component.css
  src/app/component/profile/profile-list/profile-list.component.css
  src/styles.css
Labels: Done
